index.d.ts

I believe #18 was merged too hastily. `React.ReactNode` isn't the correct type to use here because it disagrees with how [propTypes are defined](https://github.com/atomiks/tippy.js-react/blob/master/src/Tippy.js#L22-L27). Using `React.ReactNode` allows for invalid code such as this:
```jsx
<>
<Tippy content={null}>
<div />
</Tippy>
<Tippy content="foo">
{null}
</Tippy>
</>
```
The second `Tippy` element here will fail at runtime.

Narrow content and children types

---

index.d.ts
src/Tippy.js
test/Tippy.test.js

Wraps Tippy's `.enable()`, `.disable()`, `.show()`, and `.hide()` methods using props.
`isVisible` must be accompanied by `trigger="manual"`
For some reason the `isVisible` tests are failing. Anyone want to take a look? Seems like `trigger="manual"` causes a problem but I have no idea why.
Manual dev environment tests show it working as expected

Add isVisible and isEnabled props

---

index.d.ts

React does not use default export or named export, so the import did not work as expected.
Solves this issue when trying to include the library to TS project:
> TS2605: JSX element type 'Tippy' is not a constructor function for JSX elements. Property 'render' is missing in type 'Tippy'

Import React as module object

---

demo/index.js
index.d.ts
src/Tippy.js
src/utils.js
test/Tippy.test.js

I'm actually new to hooks, but I believe this follows the right principles. 
Fixes #55.

Added className prop support

---

.eslintrc
demo/index.js
src/Tippy.js
src/utils.js
test/Tippy.test.js

Merged #56 prematurely with the failing test because I thought the _test was wrong somehow_
Turns out it's just humans that are wrong, let's trust the tests more 😎

Fix className prop

---

src/Tippy.js
test/Tippy.test.js

`multiple` can safely be true by default with this wrapper since React's rendering ensures `tippy()` only called once upon mounting, there will never be duplicate tooltips
It's safely backwards-compatible.
Also adds an assertion to the test.

Remove need for explicit multiple prop

---

index.d.ts
src/Tippy.js
src/TippyGroup.js

Instead of limiting the elements to one string or one react element, would be better if it allows one (string, number, or react element) or an array of them.
Which, actually, it already works.

Fix `content` and `children` props type

---

index.d.ts

Missing types after d08169019f62382a9c6374b7eab99b3ce4193d7f

Re-export tippy core in typings file

---

src/Tippy.js
test/Tippy.test.js

Mentioned a while ago in #51, especially with hot-reloading when changing the child tag type, there are problems. React remounts when the `children.type` changes (e.g. changing from `<span>` to `<div>`), which is when we need to create a new instance

Account for children update

---

src/Tippy.js
test/Tippy.test.js

Background
---
Normally, we don't update the Tippy instance's options until the third render, because it is assumed that no options change between the first and second (which is automatic due to `setMounted`())
However, this assumption isn't entirely correct, as attempting to update options via props after the first render but before the second will result in the prop being passed but the option not actually updating. An example of such a case is setting an option with a ref.
Method
---
To fix this, I:
- allow the Tippy instance to update its options on the 2nd render and afterwards instead of the 3rd
- add a test case for updating an option via a ref and asserting that it is set correctly on the second render
Closes #117

Allow instance options to update on 2nd render and afterwards instead of 3rd

---

index.d.ts
package-lock.json
package.json

Will this work @KubaJastrz 
> The new prettier formatting didn't format this file after the change..

Specify Partial<Props> in types

---

index.d.ts
src/Tippy.js
src/TippySingleton.js
src/hooks.js
test/TippySingleton.test.js

- Since it's its own element, `className` prop support is needed.
- `enabled` and `visible` props don't really make sense for though
- `plugins` prop should be possible but needs to be supported in core, but I don't know if it works properly yet. There's likely conflicts or problems with how it works.

Add className support to <TippySingleton />

---

src/Tippy.js
src/TippySingleton.js
src/hooks.js
test/Tippy.test.js
test/TippySingleton.test.js

Since the previous instance gets destroyed when `children.type` (`<Tippy />`) and `children.length` (`<TippySingleton />`) change, the `className` never gets applied - we have to add it as a dependency.

Sync className with children changes (create effect)

---

README.md
demo/index.js
src/Tippy.js
src/hooks.js
src/index.js
test/useSingleton.test.js

This addresses #132 — it hasn't been fully tested, but I just wanted to push up what I have for any feedback/discussion. The basic usage is:
```jsx
import Tippy, {useSingleton} from '@tippy.js/react';
function Demo() {
const singleton = useSingleton({delay: 500});
return (
<div>
<Tippy singleton={singleton} content="Tooltip 1">
<button>One</button>
</Tippy>
<Tippy singleton={singleton} content="Tooltip 2">
<button>Two</button>
</Tippy>
<Tippy singleton={singleton} content="Tooltip 3">
<button>Three</button>
</Tippy>
</div>
);
}
```

Introduce a useSingleton hook

---

index.d.ts

Fixes #134 
This ignores `[key: string]: any` from `Props` interface, allowing autocomplete and type validation to actually work in this package. (It works fine in `tippy.js` core [autocomplete & types validation works] but not when extended here, idk why I'm not good with TS)
--- 
Then we need to add back in the index signature for each of the extended interfaces so plugin props don't error (without needing to make your own type).
To make your own type for plugin props like `followCursor` which don't exist on `Props`, you need to make your own function type, like this, I think:
```tsx
import Tippy, {TippyProps} from '@tippy.js/react';
import {followCursor, FollowCursorProps} from 'tippy.js';
const TippyExtended: React.FC<TippyProps & FollowCursorProps> = ({
plugins,
...props
}) => <Tippy …
```

Use KnownProps to ignore index signature

---

index.d.ts
src/Tippy.js
src/TippySingleton.js
src/hooks.js
src/util-hooks.js
test/TippySingleton.test.js
test/useSingleton.test.js

As I mentioned before, `visible` doesn't make sense for singletons, but `enabled` does. But this brings up an interesting problem: how do you make `visible` or `enabled` work for sub-tippies that are part of the singleton? I think with `group`, that previously worked since they were individual instances. This probably requires changes in core.
Since there's now common code, I've extracted these into separate hooks and created `util-hooks` (used internally) and `hooks` (exported by the package) directories.

Support `enabled` prop in singletons

---

src/Tippy.js

👋
Those props are added by babel-preset-react in dev environment (by @babel/plugin-transform-react-jsx-self and @babel/plugin-transform-react-jsx-source)
Documentation: https://babeljs.io/docs/en/babel-preset-react/
But they are passed directly to tippy and currently we have the warnings everywhere I am using it in my development environment:

Filter __source and __self dev props

---

src/Tippy.js
test/Tippy.test.js

There was a mistake here as we weren't passing the dep in an array, rather by itself. (We need that TypeScript rewrite asap 😅)
Babel loose mode uses `className.concat(dep)` so that's why there is no error when using the package (i.e. the dependency array was equivalent to not being there at all - re-running every time for component children since it was concating the forwardRef object), but there's an error in the demo when using a component as a child - not sure why the transform is different there.
It also doesn't error in the tests because of the babel transform, I think.

fix: extract deps to constant

---

index.d.ts
package-lock.json
package.json
src/Tippy.js
src/TippySingleton.js
src/hooks.js
src/util-hooks.js

chore: defer plugins passing to props

---

README.md

Added single quotes (') to avoid 'The splatting operator '@' cannot be used to reference variables in an expression.' error when windows users copy and paste the installation commands to PowerShell.
Error message:
```
At line:1 char:10
+ yarn add @tippy.js/react
+          ~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@tippy' can be used only as an argument to a command. To   
reference variables in an expression use '$tippy'.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : SplattingNotPermitted
```

Package installation commands updated.

---

src/Tippy.js

@tyteen4a03  @tony 
Does this fix the issue?

fix: portal SSR

---

demo/index.js
src/Tippy.js
src/useSingleton.js
test/__snapshots__/Tippy.test.js.snap

Fixes console warning #232  (while maintaining the fix for #227) 
Caveat: affects perf as it causes another double render, this time in the `useSingleton` hook.

fix: revert back to mounted call

---

README.md
demo/index.js
index.d.ts
src/Tippy.js
test/Tippy.test.js

Closes https://github.com/atomiks/tippyjs-react/issues/213
@potty 
@reywright
Use cases:
1. React.RefObject
```jsx
function App() {
const ref = useRef();
return (
<>
<button ref={ref} />
<Tippy reference={ref} />
</>
);
}
```
2. Element
```jsx
function App() {
const [element, setElement] = useState(null);
return (
<>
<button ref={setElement} />
<Tippy reference={element} />
</>
);
}
```

feat: reference prop

---

index.d.ts

Typescript - added type definition for `ref` prop in TippyProps

---

src/Tippy.js
test/Tippy.test.js

This change allows to do the following:
```
<Tippy render={(attrs, content, instance) =>
<button onMousLeave={instance.hideWithInteractivity}>foo</button>
}>bar</Tippy>
```
Without this change, one needs to manually store the instance using the `onCreate` prop

feat: expose instance argument from render prop

---

src/useSingleton.js
test/useSingleton.test.js

This MR updates the singleton logic so that `setInstances` is called when Tippys are added or removed.
This means that you can now dynamically add Tippys when you have a singleton (previously all Tippys needed to be declared when creating the singleton).
This should fix the issue raised here:
https://github.com/atomiks/tippyjs-react/issues/253
---
@atomiks Let me know if you want any tweaks to this MR before merging it (e.g. more tests, docs changes, etc).

Singleton now works when Tippys are added
